### ISSUE TITLE
License/terms of use?

### ISSUE THREAD

**Issue by AustinRochford** [polygraph-cool/last-two-minute-report#34]
I've done some statistical analysis of a subset of this data and think it makes a really interesting illustration of item response theory.  I'd like to write this up on my blog (austinrochford.com) and didn't see a license in the repo, so wanted to get your thoughts before committing to a writeup.  Of course I would cite you, this repo, and the pudding.cool publications derived from this data set.

Thanks so much for taking the time to compile this data set; it's amazing!

**Comment by russellgoldenberg** [comment]
Just added a MIT license, thanks!

Go ahead and do whatever you want, the data is public. It updates pretty much daily fyi. Send me a link when you're done!

**Comment by AustinRochford** [comment]
I figured you wouldn't mind since you had posted to GitHub, but really appreciate all the work you did to make this data conveniently accessible, so wanted to double check.

Will certainly send you a link when done in the next few weeks.
